### ISSUE TITLE
Using Add-FnRef for parameter that requires an Int32 fails

### ISSUE THREAD

**Issue by embusalacchi** [scrthq/VaporShell#66] opened 2020-02-12 21:15 UTC
I'm setting up an FSx cloudformation and when using the Add-FnRef to pass in the -StorageCapacity there is an error: 

> New-VSFSxFileSystem : Cannot process argument transformation on parameter 'StorageCapacity'. Cannot convert the "@{Ref=FileSystemSize}" value of type "Vaporshell.Function.Ref" to type "System.Int32".
> At /Users/ebusalacchi/Documents/GitHub/aws/cloudformations/pti/fsx.ps1:125 char:26
>  -StorageCapacity (Add-FnRef -Ref "FileSystemSize") `

```
    (New-VSFSxFileSystem -LogicalId "FSX" `
        -DependsOn "FSxSecurityGroup","FSxKMSKey" `
        -FileSystemType "WINDOWS" `
        -KmsKeyId (Add-FnRef -Ref "FSX") `
        -StorageCapacity (Add-FnRef -Ref "FileSystemSize") `
        -SubnetIds (Add-FnImportValue -ValueToImport (Add-FnSub -String "`${VPCStackName}-PrivateSubnetAZ1")) `
        -SecurityGroupIds (Add-FnRef -Ref "FSxSecurityGroup") `
        -WindowsConfiguration @{
            ActiveDirectoryId = (Add-FnImportValue -ValueToImport (Add-FnSub -String "`${Environment}-ActiveDirectoryId"))
            ThroughputCapacity = (Add-FnRef -Ref "FileSystemThroughput")
            WeeklyMaintenanceStartTime = "1:12:30"  # Monday 07:30 ET
            DailyAutomaticBackupStartTime = "12:00" # 07:00AM ET
            AutomaticBackupRetentionDays = 30 
        }
    )
```

The param definition:
```
    (New-VaporParameter -LogicalId "FileSystemSize" `
        -Type "Number" `
        -Default 500 `
        -MinValue 300 `
        -MaxValue 65536 ),
```

**Comment by scrthq** [comment] 2020-02-17 23:42
Hey @embusalacchi - Thanks for opening this up! I believe I know what the issue is, checking it out now and should hopefully have a fix for you today if it is what I believe it is. I'll keep you updated here!

**Comment by scrthq** [comment] 2020-02-17 23:58
Fix incoming shortly in version 2.9.5!

**Comment by scrthq** [comment] 2020-02-18 04:54
Fixed in v2.9.5! Please update and let me know if you are still having issues @embusalacchi 🙂 

![image](https://user-images.githubusercontent.com/12724445/74705083-3f006e00-51d8-11ea-990f-7256a931407f.png)

**Closed by scrthq** 2020-02-18 04:54 UTC
Labels: bug

**Comment by embusalacchi** [comment] 2020-02-18 18:26
This is fantastic - thank you for fixing this so quickly!  Love the tool - it's made dealing with YAML much more tolerable.

**Comment by scrthq** [comment] 2020-02-18 19:44
I'm glad to hear!!! That's awesome :-)

Just an FYI as well - I'm ironing out the kinks to have weekly scheduled releases taking place so that the module itself stays up to date with the current CloudFormation specification sheet. Should see a lot less gap between new functionality in CloudFormation and VaporShell :-)
